=== JulienBreton/spaceInvaders/data/xml/niveau.dtd
<!ELEMENT jeu (armee+, ennemi+, armeEnnemie, ennemiBonus)>
<!ELEMENT armee (#PCDATA)>
<!ATTLIST armee
          Acceleration CDATA #REQUIRED
          DebutCourseX CDATA #REQUIRED
          DepartArmeeX CDATA #REQUIRED
          DepartArmeeY CDATA #REQUIRED
          EnnemisParlignes CDATA #REQUIRED
          EspaceY_EntreEnnemis CDATA #REQUIRED
          FinCourseY CDATA #REQUIRED
          HauteurSautYEnnemis CDATA #REQUIRED
          Index CDATA #REQUIRED
          NombreDeSautsEnnemis CDATA #REQUIRED
          NombreEnnemis CDATA #REQUIRED
          PosFinEnnemisType1 CDATA #REQUIRED
          PosFinEnnemisType2 CDATA #REQUIRED
          PosFinEnnemisType3 CDATA #REQUIRED
          VitesseArmeeY CDATA #REQUIRED>
<!ELEMENT ennemi (#PCDATA)>
<!ATTLIST ennemi
          Index CDATA #REQUIRED
          Points CDATA #REQUIRED
          TailleEnnemiX CDATA #REQUIRED
          TailleEnnemiY CDATA #REQUIRED
          Texture1 CDATA #REQUIRED
          Texture2 CDATA #REQUIRED>
<!ELEMENT armeEnnemie (#PCDATA)>
<!ATTLIST armeEnnemie
          DepartY_ParticulesTirEnnemi CDATA #REQUIRED
          DureeVieParticulesTirEnnemi CDATA #REQUIRED
          EspaceY_EntreParticulesTirEnnemi CDATA #REQUIRED
          NbParticulesTirEnnemi CDATA #REQUIRED
          TailleTirEnnemi CDATA #REQUIRED
          TempsReinitParticulesTirEnnemi CDATA #REQUIRED
          VitesseTirEnnemiY CDATA #REQUIRED>
<!ELEMENT ennemiBonus (#PCDATA)>
<!ATTLIST ennemiBonus
          Index CDATA #REQUIRED
          Points CDATA #REQUIRED
          TailleEnnemiBonusX CDATA #REQUIRED
          TailleEnnemiBonusY CDATA #REQUIRED
          Texture CDATA #REQUIRED>

=== JulienBreton/spaceInvaders/data/xml/niveau.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE jeu SYSTEM "niveau.dtd">
<jeu>
	<armee Index="1" VitesseArmeeY="10" Acceleration="2" DepartArmeeX="0" DepartArmeeY="0" DebutCourseX="0" FinCourseY="800" EnnemisParlignes="11" EspaceY_EntreEnnemis="10" NombreDeSautsEnnemis="12" HauteurSautYEnnemis="1234560" NombreEnnemis="55" PosFinEnnemisType1="21" PosFinEnnemisType2="43" PosFinEnnemisType3="54">
	</armee>
	
	 <armee Index="2" VitesseArmeeY="15" Acceleration="4" DepartArmeeX="0" DepartArmeeY="0" DebutCourseX="0" FinCourseY="800" EnnemisParlignes="10" EspaceY_EntreEnnemis="10" NombreDeSautsEnnemis="12" HauteurSautYEnnemis="1234560" NombreEnnemis="30" PosFinEnnemisType1="9" PosFinEnnemisType2="19" PosFinEnnemisType3="29">
	</armee>


	<ennemi Index="1" Points="10" Texture1="data/images/invader1.tga" Texture2="data/images/invader1bis.tga" TailleEnnemiX="35" TailleEnnemiY="35">
	</ennemi>

	<ennemi Index="2" Points="20" Texture1="data/images/invader2.tga" Texture2="data/images/invader2bis.tga" TailleEnnemiX="135" TailleEnnemiY="135">
	</ennemi>

	<ennemi Index="3" Points="30" Texture1="data/images/invader3.tga" Texture2="data/images/invader3bis.tga" TailleEnnemiX="55" TailleEnnemiY="55">
	</ennemi>

	<armeEnnemie VitesseTirEnnemiY="2" TailleTirEnnemi="6" NbParticulesTirEnnemi="50" EspaceY_EntreParticulesTirEnnemi="0" TempsReinitParticulesTirEnnemi="0.01" DureeVieParticulesTirEnnemi="0.5" DepartY_ParticulesTirEnnemi="0">
	</armeEnnemie>

	<ennemiBonus Index="1" Points="50" Texture="data/images/vaisseaubonus.tga" TailleEnnemiBonusX="109" TailleEnnemiBonusY="68">
	</ennemiBonus>
</jeu>
